install:
	npm install

start:
	npm start

start-dev:
	npm run start:dev

start-staging:
	npm run start:staging

start-prod:
	npm run start:prod

build:
	npm run build

build-dev:
	npm run build:dev

build-staging:
	npm run build:staging

build-prod:
	npm run build:prod

test:
	npm test

lint:
	npm run lint

format:
	npm run format

prepare:
	npm run prepare

.PHONY: install start start-dev start-staging start-prod build build-dev build-staging build-prod test lint format prepare
